### ISSUE TITLE
My Solar System Master Checklist

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/my-solar-system#1]
# My Solar System master checklist

## Design
- [x] **Sim folder and design doc created** (Date: 09/22/2020) 
  - [x] Create sim folder in [PhET Sim Design Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc) using phet-docs account
  - [x] Place design doc in the sim folder
- [x] **Sim suggestions doc reviewed** [suggestions doc](https://phet.unfuddle.com/a#/projects/9404/notebooks/3863/pages/105821)
   - [x] *If a Port:* Unfuddle tickets reviewed ([searching tickets](https://github.com/phetsims/phet-info/blob/master/issue-info/unfuddle-ticket-search.md))
- [x] **Learning goals and standards identified** (Date: Feb/2021)
- [x] **Design concept complete**  (Date: Feb/2021)
- [x] **Wireframes complete** (Date: //)
- [x] **Mockups complete** (Date: //)
  - [x] Mockups checked for colorblind and greyscale
- <s>**Features for PhET-iO discussion** </s>  (N/A for this release.)
- [x] **Interviews complete** (Date: //)
  - [x] Results reported to team
  - [x] Notes pasted into design doc
  - [x] Back-up of interviews
- [x] **Lead designer "sign off"** (Date: //)
  - [x] Performance acceptable
  - [x] Carefully review ?showPointerAreas
  - [x] No new feature requests
- [x] **Pre-publication items**
  - [x] Auxilary screenshots (up to 3 additional)
  - [x] Screen-specific screenshots for metadata service (see [naming convention](https://github.com/phetsims/website/issues/1322#issuecomment-1010320827))
  - [x] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [x] Accessibility features
  - [x] Email announcement language
  - [x] Teacher Guide created, uploaded, and added to sim design folder
  - [x] [LoL icons](https://docs.google.com/document/d/1GmLNE31gs8hQYGze3xwmN9k7B6gu7lQ7wJe2phqdH9Y/edit) for each screen created and uploaded to Drive - #186 
  - [x] [LoL metadata](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=562591429) for each screen (description, vocab words, questions for before/after sim use) - #186 
- [x] **Make sim visible on website** 
   - [x] Clear "Metadata caches" on the [Basic Administration Caches](https://phet.colorado.edu/?wicket:bookmarkablePage=:edu.colorado.phet.website.admin.AdminCachesPage) page
- [x] **Post-publication items**
  - [x] *If a Port:* Review legacy gold star activities, copy over if appropriate
  - [x] Share new features, design challenges, and treats with group!
  - [x] Email announcement
  - [x] Deliver to [Legends of Learning](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) - #186 
  - [x] Create "sim primer" issue - https://github.com/phetsims/my-solar-system/issues/185
  - <s> Hold postmortem if applicable (Date: //)</s>
## Implementation
- [x] **Repository created** (Date: 9/22/2020)
  - [x] Simulation added to [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)
  - [x] Use `grunt create-sim` in perennial (see `--help` for arguments) to create the repository structure
  - [x] Collaborators added (Developer team, QA team, designers, etc)
  - [x] standard GitHub label set applied
  - [x] repository added to perennial/data/active-repos
- [x] **Development started** (Date: //)
- [x] **Sim is "feature complete"** (Date: //)
- [x] **Code review completed** (Date: //)
- [x] **Pre-publication items**
  - [x] Main screenshot (read [this](https://github.com/phetsims/QA/blob/master/doc/qa-book.md#screenshots))
  - [x] Verify credits with lead (Team, Contributors, QA, Graphic Arts, Sound Design, any Thanks)
  - [x] Add CT tests for public query parameters
- [x] **Published** (Date: 5/12/23)
  - <s>Mark the sim as published in [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)</s> (Skipped -- file doesn't contain publication status)

## QA
- [x] *If a Port:* **Legacy sim tested for bugs**; issues reported in repo
- [x] **Dev testing started** (Date: 4/5/23)
- [x] **Dev testing completed** (Date: 4/14/23)
- [x] **First RC published** (Date: 4/28/23)
  - [x] Test matrices put in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
- [x] **RC testing completed** (Date: 5/9/23)

**Comment by arouinfar** [comment]
@DianaTavares I completed the checklist and moved the remaining items to their own issues. Closing.
