### ISSUE TITLE
ToDo list of small updates 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/my-solar-system#81]
@AgustinVallejo create this list of small changes needed for MSS:

- [ ] 3rd law scene, a vs T graph: reduce the negative space of the labels of the graph and the values (issue #78)
- [ ] 3rd law scene: Semimajor Axis (a) and Period checkboxes are not working 
- [ ] Kepler's Law screen: Force checkbox is not working
- [ ] Lab screen: review all the presets while the sim is in &dev size, some trajectories pass below the mass panel (issue #72 )
- [ ] 1st law scene: semiaxis checkbox is not working. Should display what is presented in the picture:
![image](https://user-images.githubusercontent.com/26031501/214370482-eec0022d-62a3-43f9-95be-adb2b294aaf7.png)

- [ ] 1st law scene: Eccentricity checkbox is not working completely. It needs to display in the orbit the next information:
![image](https://user-images.githubusercontent.com/26031501/214370800-6da9584c-6f57-450c-aff3-ba48d82f1524.png)

- [ ] 1st law scene: String checkbox is not working completely. It needs to display in the orbit the labels of d1 and 22, and the animation of how the string is changing at the bottom of the screen, like is shown in the next picture:
![image](https://user-images.githubusercontent.com/26031501/214371571-5abd5a0b-a532-485e-bf00-74c60f0219eb.png)

- [ ] All the screens: Planets shouldn't be allowed to be dragged behind the panels 
- [ ] Kepler's Law screen: not allow building orbits that not fit in the play area. The idea is to show an error text when the orbit is big:
![image](https://user-images.githubusercontent.com/26031501/214372928-0c2644f7-169a-4fac-85c3-4b5783958470.png)

- [ ] Kepler's Law screen: Values checkbox is not working. Delete the velocity value of the sun and add the values of a, b, c, strings in the first law  and area in the second law 8like is shown in the pictures below, issue #75 ).
![image](https://user-images.githubusercontent.com/26031501/214373398-5a6040d2-6972-4150-820e-28a1b23d3648.png)

- [ ]  1st law scene:  scene icon (issue #74) and foci icon are incorrect. 
- [ ] All the screens: Play button. Fast, normal and Slow text look little bigger that the rest of text in the sim and need left aligment (issue #71)

**Comment by DianaTavares** [comment]
I find another issue:

- [ ] 1st law scene: String checkbox is inside foci because it should be visible only when foci are active, then the behavior shown in the picture is not correct: 
![image](https://user-images.githubusercontent.com/26031501/214701315-21637c52-2860-43f5-aca9-cc07a631c61f.png)

**Comment by DianaTavares** [comment]
- [ ] One more thing, the Swept Area Graph need it vertical label:
![image](https://user-images.githubusercontent.com/26031501/217105173-ccccb0ec-fa7d-416e-8837-c2fa021a4d95.png)
